const { alpha, commands } = require("./plugins");
let config = require("../config");

const { runtime, clockString } = require("./runtime");
const {
  getBuffer,
  decodeJid,
  parseJid,
  parsedJid,
  getJson,
  isIgUrl,
  isUrl,
  getUrl,
  qrcode,
  secondsToDHMS,
  formatBytes,
  sleep,
  AddMp3Meta,
  Bitly,
  isNumber,
  getRandom,
  findMusic,
  toAudio,
  readQr,
  getLyrics,
  isAdmin,
} = require("./functions");
const {
  tiktokdl,
  twitter,
  photoleap,
  fbdown,
  igdl,
  stream2buffer,
  searchYT,
  downloadMp3,
  downloadMp4,
  TTS,
  TRT,
  getYTInfo,
} = require("./scrapper");
const { serialize, downloadMedia } = require("./serialize");
const Greetings = require("./Greetings");
module.exports = {
  toAudio,
  runtime,
  clockString,
  isPrivate: config.WORK_TYPE.toLowerCase() === "private",
  PREFIX:
  !config.HANDLERS || config.HANDLERS == "false" || config.HANDLERS == "null"
    ? ""
    : config.HANDLERS.includes("[") && config.HANDLERS.includes("]")
      ? config.HANDLERS[2]
      : config.HANDLERS.trim(),
  Greetings,
  isAdmin,
  serialize,
  getLyrics,
  readQr,
  downloadMedia,
  Function: alpha,
  alpha,
  commands,
  getBuffer,
  decodeJid,
  parseJid,
  parsedJid,
  getJson,
  isIgUrl,
  isUrl,
  getUrl,
  qrcode,
  secondsToDHMS,
  formatBytes,
  tiktokdl,
  twitter,
  photoleap,
  fbdown,
  igdl,
  stream2buffer,
  searchYT,
  downloadMp3,
  downloadMp4,
  TTS,
  TRT,
  getYTInfo,
  sleep,
  AddMp3Meta,
  Bitly,
  isNumber,
  getRandom,
  findMusic,
};
